version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: onlinebanking-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlinebanking
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: .
    container_name: onlinebanking-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/onlinebanking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"
    restart: unless-stopped
